version: '3'
services:
    flaskapp:
        build: ./Flask
        depends_on:
            - redis
        hostname: flaskapp
    redis:
        image: redis
        hostname: redis
    nginxfiles: 
        build: ./nginxfiles
        #ports: 
        #    - "80:80"
        hostname: nginxfiles
        volumes: 
            - ./nginxfiles/images:/data/images
    nginxproxy: 
        build: ./nginxproxy
        ports: 
            - "80:80"
        hostname: nginxproxy
        depends_on: 
            - flaskapp
            - nginxfiles