version: '3'
services:
    flaskapp:
        build: ./Flask
        #ports:
        #    - "5000:5000"
        depends_on:
            - redis
        hostname: flaskapp
    redis:
        image: redis
        hostname: redis
    nginxfiles: 
        build: ./nginxfiles
        #ports: 
        #    - "80:80"
        hostname: nginxfiles
    nginxproxy: 
        build: ./nginxproxy
        ports: 
            - "8081:8081"
            - "5000:5000"
            - "80:80"
        hostname: nginxproxy
        depends_on: 
            - flaskapp
            - nginxfiles